# Generated by Django 2.1.7 on 2019-05-31 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=3, null=True)),
                ('fonte', models.CharField(default='wd', max_length=255, verbose_name='Fonte della Label/Sameas')),
            ],
        ),
        migrations.CreateModel(
            name='Wikidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('q', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wikipedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=3, null=True)),
                ('wikidata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikidata_interlink.Wikidata')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='wikidata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikidata_interlink.Wikidata'),
        ),
    ]
