# Generated by Django 2.1.7 on 2019-05-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata_interlink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='url',
        ),
    ]
