# Generated by Django 2.1.7 on 2019-06-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata_interlink', '0002_remove_label_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikidata',
            old_name='nome',
            new_name='keyword',
        ),
        migrations.AlterField(
            model_name='label',
            name='wikidata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata_interlink.Wikidata'),
        ),
        migrations.AlterField(
            model_name='wikipedia',
            name='wikidata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata_interlink.Wikidata'),
        ),
    ]
